In [1]:
### concatenate dsis's data 
### remapping headers using dso's mapping

import pandas as pd
import numpy as np

import pprint
pp = pprint.PrettyPrinter(indent=2)

from bson.objectid import ObjectId

In [2]:
null = None

### variables

In [3]:
dsi_data_01 = {
    "oid_dsi" : ObjectId("5c3758200a828696f74fcfe3"),
    "data_raw" : {
        "f_col_headers" : [ 
            {
                "f_coll_header_val" : "_id",
                "f_coll_header_text" : "_id"
            }, 
            {
                "f_coll_header_val" : "added_at",
                "f_coll_header_text" : "added_at"
            }, 
            {
                "f_coll_header_val" : "adresse du projet",
                "f_coll_header_text" : "adresse du projet"
            }, 
            {
                "f_coll_header_val" : "image(s) du projet",
                "f_coll_header_text" : "image(s) du projet"
            }, 
            {
                "f_coll_header_val" : "link_data",
                "f_coll_header_text" : "link_data"
            }, 
            {
                "f_coll_header_val" : "link_src",
                "f_coll_header_text" : "link_src"
            }, 
            {
                "f_coll_header_val" : "partenaires du projet",
                "f_coll_header_text" : "partenaires du projet"
            }, 
            {
                "f_coll_header_val" : "résumé du projet",
                "f_coll_header_text" : "résumé du projet"
            }, 
            {
                "f_coll_header_val" : "spider_id",
                "f_coll_header_text" : "spider_id"
            }, 
            {
                "f_coll_header_val" : "structure porteuse",
                "f_coll_header_text" : "structure porteuse"
            }, 
            {
                "f_coll_header_val" : "tags",
                "f_coll_header_text" : "tags"
            }, 
            {
                "f_coll_header_val" : "titre du projet",
                "f_coll_header_text" : "titre du projet"
            }, 
            {
                "f_coll_header_val" : "website",
                "f_coll_header_text" : "website"
            }
        ],
        "f_data" : [ 
            {
                "_id" : "5bcdc4dc3ba14c6ce4c3426e",
                "added_at" : 1540211930.05566,
                "adresse du projet" : [ 
                    "2 633 276 €", 
                    ": Lorraine", 
                    "FEDER", 
                    "2013", 
                    "842 634 €", 
                    "Lorraine", 
                    "FEDER", 
                    "2013"
                ],
                "image(s) du projet" : [ 
                    "http://www.europe-en-france.gouv.fr/var/europe_en_france/storage/images/rendez-vous-compte/projets-exemplaires/le-projet-fibrastral-developpe-une-alternative-a-la-fibre-de-verre/301863-1-fre-FR/Le-projet-Fibrastral-developpe-une-alternative-a-la-fibre-de-verre_projet_pictolisting.jpg", 
                    "http://www.europe-en-france.gouv.fr/var/europe_en_france/storage/images/rendez-vous-compte/projets-exemplaires/le-projet-fibrastral-developpe-une-alternative-a-la-fibre-de-verre/301863-1-fre-FR/Le-projet-Fibrastral-developpe-une-alternative-a-la-fibre-de-verre_projet_logo.jpg"
                ],
                "link_data" : "http://www.europe-en-france.gouv.fr/Rendez-vous-compte/Projets-exemplaires/Le-projet-Fibrastral-developpe-une-alternative-a-la-fibre-de-verre/(offset)/10/(viewtheme)/0/(viewregion)/0/(viewfonds)/0/(annee)/0",
                "link_src" : "http://www.europe-en-france.gouv.fr/Rendez-vous-compte/Projets-exemplaires/(offset)/10/(annee)/0/(viewtheme)/0/(viewregion)/0/(viewfonds)/0",
                "partenaires du projet" : [ 
                    "2 633 276 €", 
                    ": Lorraine", 
                    "FEDER", 
                    "2013", 
                    "842 634 €", 
                    "Lorraine", 
                    "FEDER", 
                    "2013"
                ],
                "résumé du projet" : [ 
                    "La fibre de verre, considérée comme un matériau polluant, est issue du pétrole et entre dans la composition de certaines matières plastiques. Créer une alternative à cette fibre est une idée porteuse et innovante car elle est à la fois écologique, génératrice d’économie d’énergie et créatrice d’emplois. Pour toutes ces raisons, l’Union européenne a choisi d’appuyer ce projet à hauteur de 842 634 euros, sur un budget total de 2,6 millions d’euros."
                ],
                "spider_id" : "5ac3505d0a82860f68d16288",
                "structure porteuse" : [ 
                    "Thématique(s) : Attractivité du territoire ; Les grands projets européens 2007-2013 ; Services au public ; Transports ; Urbain", 
                    "Thématique(s) : Attractivité du territoire ; Eco-tourisme", 
                    "Thématique(s) : Les grands projets européens 2007-2013 ; TIC", 
                    "Thématique(s) : Attractivité du territoire ; Recherche et Innovation", 
                    "Attractivité du territoire ; Recherche et Innovation", 
                    "Bénéficiaire :", 
                    "Thématique(s) :", 
                    "Université de Lorraine"
                ],
                "tags" : [ 
                    "Thématique(s) : Attractivité du territoire ; Recherche et Innovation", 
                    "Attractivité du territoire ; Recherche et Innovation", 
                    "Bénéficiaire :", 
                    "Thématique(s) :", 
                    "Université de Lorraine"
                ],
                "titre du projet" : [ 
                    "Le projet Fibrastral développe une alternative à la fibre de verre", 
                    "Le projet Fibrastral développe une alternative à la fibre de verre"
                ],
                "website" : null
            }, 
            {
                "_id" : "5bd0895e3ba14c3fada0550e",
                "added_at" : 1540392039.04563,
                "adresse du projet" : [ 
                    "Opération \"Eté Jeunes\" pour les 14-16 ans Gers", 
                    "32360 Jegun", 
                    "Les députés votent la substitution du CNDS par l'Agence nationale du sport et gonflent son budget", 
                    "Lancement de France Num, une plateforme nationale pour accompagner la transformation numérique des TPE", 
                    "Grande Rue - BP1", 
                    "Volet \"finances locales\" : le point après le vote par les députés de la première partie du texte", 
                    "Enfin des stats sur le poids de l'habitat privé dans les quartiers prioritaires !"
                ],
                "image(s) du projet" : null,
                "link_data" : "https://www.caissedesdepotsdesterritoires.fr/cs/ContentServer?pagename=Territoires/MCExperience/Experience&cid=1245645199070",
                "link_src" : "https://www.caissedesdepotsdesterritoires.fr/cs/ContentServer?pagename=Territoires/Page/Base-experiences",
                "partenaires du projet" : null,
                "résumé du projet" : [ 
                    "La communauté de communes Coeur de Gascogne a mis en place des chantiers d'une semaine pour les jeunes, pendant les vacances. Le succès auprès des 14-16 ans et de la population est au rendez-vous. Ces chantiers nécessitent cependant un suivi et une énergie considérables de la part des élus et encadrants bénévoles. Des problèmes de normes administratives et de sécurité persistent."
                ],
                "spider_id" : "5bc4951d3ba14c5c5620146c",
                "structure porteuse" : null,
                "tags" : [ 
                    "SOCIAL - SANTÉ", 
                    "CATÉGORIE : EXPÉRIENCES", 
                    "Social - Santé"
                ],
                "titre du projet" : [ 
                    "Opération \"Eté Jeunes\" pour les 14-16 ans"
                ],
                "website" : null
            }, 
            {
                "_id" : "5bd08f1b3ba14c3fada05cd8",
                "added_at" : 1540387431.93892,
                "adresse du projet" : [ 
                    "A Eaubonne, les jeunes en service civique aident des familles à réduire leurs factures d'énergie (95) Val-d'Oise", 
                    "Hôtel de Ville, 1 rue d'Enghien", 
                    "Les députés votent la substitution du CNDS par l'Agence nationale du sport et gonflent son budget", 
                    "Lancement de France Num, une plateforme nationale pour accompagner la transformation numérique des TPE", 
                    "95600 Eaubonne", 
                    "Volet \"finances locales\" : le point après le vote par les députés de la première partie du texte", 
                    "Enfin des stats sur le poids de l'habitat privé dans les quartiers prioritaires !"
                ],
                "image(s) du projet" : [ 
                    "https://www.caissedesdepotsdesterritoires.fr/cs/BlobServer?blobkey=id&blobnocache=false&blobwhere=1250170930698&blobcol=urldata&blobtable=MungoBlobs"
                ],
                "link_data" : "https://www.caissedesdepotsdesterritoires.fr/cs/ContentServer?pagename=Territoires/Experiences/Experiences&cid=1250279591681",
                "link_src" : "https://www.caissedesdepotsdesterritoires.fr/cs/ContentServer?pagename=Territoires/Page/Base-experiences",
                "partenaires du projet" : null,
                "résumé du projet" : [ 
                    "Chaque année depuis 2014, huit jeunes sont recrutés en service civique pendant huit mois sur la ville d’Eaubonne pour rompre l’isolement des personnes âgées et aider des familles locataires dans des logements sociaux à baisser leurs consommations d’eau et d’énergie dans une résidence d’habitat social. Le bilan positif encourage la ville à poursuivre."
                ],
                "spider_id" : "5bc4951d3ba14c5c5620146c",
                "structure porteuse" : null,
                "tags" : [ 
                    "CITOYENNETÉ - ASSOCIATIONS - JEUNESSE", 
                    "CATÉGORIE : EXPÉRIENCES", 
                    "Citoyenneté - Associations - Jeunesse"
                ],
                "titre du projet" : [ 
                    "A Eaubonne, les jeunes en service civique aident des familles à réduire leurs factures d'énergie (95)"
                ],
                "website" : [ 
                    "http://www.eaubonne.fr"
                ]
            }, 
        ]
    }
}

In [4]:
dsi_data_02 = {
    "oid_dsi" : ObjectId("5c3758690a828696f74fcfe5"),
    "data_raw" : {
        "f_col_headers" : [ 
            {
                "f_coll_header_val" : "COG",
                "f_coll_header_text" : "COG"
            }, 
            {
                "f_coll_header_val" : "ACTUAL",
                "f_coll_header_text" : "ACTUAL"
            }, 
            {
                "f_coll_header_val" : "CAPAY",
                "f_coll_header_text" : "CAPAY"
            }, 
            {
                "f_coll_header_val" : "CRPAY",
                "f_coll_header_text" : "CRPAY"
            }, 
            {
                "f_coll_header_val" : "ANI",
                "f_coll_header_text" : "ANI"
            }, 
            {
                "f_coll_header_val" : "LIBCOG",
                "f_coll_header_text" : "LIBCOG"
            }, 
            {
                "f_coll_header_val" : "norm_name",
                "f_coll_header_text" : "norm_name"
            }, 
            {
                "f_coll_header_val" : "LIBENR",
                "f_coll_header_text" : "LIBENR"
            }, 
            {
                "f_coll_header_val" : "ANCNOM",
                "f_coll_header_text" : "ANCNOM"
            }, 
            {
                "f_coll_header_val" : "CODEISO2",
                "f_coll_header_text" : "CODEISO2"
            }, 
            {
                "f_coll_header_val" : "CODEISO3",
                "f_coll_header_text" : "CODEISO3"
            }, 
            {
                "f_coll_header_val" : "CODENUM3",
                "f_coll_header_text" : "CODENUM3"
            }
        ],
        "f_data" : [ 
            {
                "COG" : "99103",
                "ACTUAL" : 1,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "NORVEGE",
                "norm_name" : "norvege",
                "LIBENR" : "ROYAUME DE NORVÈGE",
                "ANCNOM" : null,
                "CODEISO2" : "NO",
                "CODEISO3" : "NOR",
                "CODENUM3" : 578.0
            }, 
            {
                "COG" : "99103",
                "ACTUAL" : 3,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "BOUVET (ILE)",
                "norm_name" : "bouvet",
                "LIBENR" : "BOUVET (ÎLE)",
                "ANCNOM" : null,
                "CODEISO2" : "BV",
                "CODEISO3" : "BVT",
                "CODENUM3" : 74.0
            }, 
            {
                "COG" : "99104",
                "ACTUAL" : 1,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "SUEDE",
                "norm_name" : "suede",
                "LIBENR" : "ROYAUME DE SUÈDE",
                "ANCNOM" : null,
                "CODEISO2" : "SE",
                "CODEISO3" : "SWE",
                "CODENUM3" : 752.0
            }, 
            {
                "COG" : "99105",
                "ACTUAL" : 1,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "FINLANDE",
                "norm_name" : "finlande",
                "LIBENR" : "RÉPUBLIQUE DE FINLANDE",
                "ANCNOM" : null,
                "CODEISO2" : "FI",
                "CODEISO3" : "FIN",
                "CODENUM3" : 246.0
            }, 
            {
                "COG" : "99110",
                "ACTUAL" : 1,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "AUTRICHE",
                "norm_name" : "autriche",
                "LIBENR" : "RÉPUBLIQUE D'AUTRICHE",
                "ANCNOM" : null,
                "CODEISO2" : "AT",
                "CODEISO3" : "AUT",
                "CODENUM3" : 40.0
            }, 
            {
                "COG" : "99112",
                "ACTUAL" : 1,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "HONGRIE",
                "norm_name" : "hongrie",
                "LIBENR" : "RÉPUBLIQUE DE HONGRIE",
                "ANCNOM" : null,
                "CODEISO2" : "HU",
                "CODEISO3" : "HUN",
                "CODENUM3" : 348.0
            }, 
            {
                "COG" : "99115",
                "ACTUAL" : 2,
                "CAPAY" : null,
                "CRPAY" : null,
                "ANI" : null,
                "LIBCOG" : "TCHECOSLOVAQUIE",
                "norm_name" : "tchecoslovaquie",
                "LIBENR" : "TCHÉCOSLOVAQUIE",
                "ANCNOM" : null,
                "CODEISO2" : null,
                "CODEISO3" : null,
                "CODENUM3" : null
            }, 
        ]
    }
}

In [5]:
dso_col_headers = {
    "f_col_headers" : [ 
        {
            "oid_dmf" : ObjectId("5c056a4f0a82861e733374ef"),
            "open_level_show" : "open_data",
            "name" : "Identification du marché public"
        }, 
        {
            "oid_dmf" : ObjectId("5ba664030a82860745d51fdd"),
            "open_level_show" : "open_data",
            "name" : "Adresse_"
        }, 
        ### -------------------------
        {
            "oid_dmf" : ObjectId("5c10450f0a8286a6f6522e02"),
            "open_level_show" : "open_data",
            "name" : "Date de la notification du marché"
        }, 
        {
            "oid_dmf" : ObjectId("5c10456e0a8286a6f6522e04"),
            "open_level_show" : "private"
            ### missing name
        }, 
        {
            "oid_dmf" : ObjectId("5bfe87520a82866842b7db96"),
            "open_level_show" : "collective",
            "name" : "Nom de l'acheteur"
        }, 
        {
            "oid_dmf" : ObjectId("5c10443c0a8286a6f6522dfe"),
            "open_level_show" : "open_data",
            "name" : "Code du lieu d'exécution"
        }, 
        {
            "oid_dmf" : ObjectId("5c1044e90a8286a6f6522e01"),
            "open_level_show" : "commons",
            "name" : "Durée initiale du marché"
        }
    ],
}

In [6]:
dso_mapping = {
    "dsi_to_dmf" : [ 
        
        {
            "dsi_header" : "added_at",
            "oid_dsi" : ObjectId("5c3758200a828696f74fcfe3"),
            "oid_dmf" : ObjectId("5c3777d10a8286e874b46075") ### not present in f_col_headers
        }, 
        {
            "dsi_header" : "adresse du projet",
            "oid_dsi" : ObjectId("5c3758200a828696f74fcfe3"),
            "oid_dmf" : ObjectId("5ba664030a82860745d51fdd") # OK in f_col_headers
        }, 
        {
            "dsi_header" : "_id",
            "oid_dsi" : ObjectId("5c3758200a828696f74fcfe3"),
            "oid_dmf" : ObjectId("5c056a4f0a82861e733374ef") # OK in f_col_headers
        }, 
        {
            "dsi_header" : "link_data",
            "oid_dsi" : ObjectId("5c3758200a828696f74fcfe3"),
            "oid_dmf" : ObjectId("5bf4183f0a8286180b53183c") ### not present in f_col_headers
        }, 
        #### ------------------------------------ #### 
        {
            "dsi_header" : "CAPAY",
            "oid_dsi" : ObjectId("5c3758690a828696f74fcfe5"),
            "oid_dmf" : ObjectId("5c10443c0a8286a6f6522dfe")
        }, 
        {
            "dsi_header" : "ACTUAL",
            "oid_dsi" : ObjectId("5c3758690a828696f74fcfe5"),
            "oid_dmf" : ObjectId("5ba664030a82860745d51fdd")
        }
    ],
    "dmf_to_rec" : [],
    "dmf_to_open_level" : [ 
        {
            "oid_dmf" : ObjectId("5c056a4f0a82861e733374ef"),
            "open_level_show" : "open_data"
        }, 
        {
            "oid_dmf" : ObjectId("5c10450f0a8286a6f6522e02"),
            "open_level_show" : "open_data"
        }, 
        {
            "oid_dmf" : ObjectId("5c10456e0a8286a6f6522e04"),
            "open_level_show" : "private"
        }, 
        {
            "oid_dmf" : ObjectId("5bfe87520a82866842b7db96"),
            "open_level_show" : "collective"
        }, 
        {
            "oid_dmf" : ObjectId("5ba664030a82860745d51fdd"),
            "open_level_show" : "open_data"
        }, 
        {
            "oid_dmf" : ObjectId("5c10443c0a8286a6f6522dfe"),
            "open_level_show" : "open_data"
        }, 
        {
            "oid_dmf" : ObjectId("5c1044e90a8286a6f6522e01"),
            "open_level_show" : "commons"
        }
    ]
}

### local mappers

In [7]:
### store f_col_headers apart
headers_dso = dso_col_headers["f_col_headers"] 
#pp.pprint(headers_dso)

In [8]:
df_mapper_col_headers = pd.DataFrame(headers_dso)
df_mapper_col_headers = df_mapper_col_headers.set_index("oid_dmf")
df_mapper_col_headers

                                                       name open_level_show
oid_dmf
5c056a4f0a82861e733374ef    Identification du marché public       open_data
5ba664030a82860745d51fdd                           Adresse_       open_data
5c10450f0a8286a6f6522e02  Date de la notification du marché       open_data
5c10456e0a8286a6f6522e04                                NaN         private
5bfe87520a82866842b7db96                  Nom de l'acheteur      collective
5c10443c0a8286a6f6522dfe           Code du lieu d'exécution       open_data
5c1044e90a8286a6f6522e01           Durée initiale du marché         commons

In [9]:
len(df_mapper_col_headers.index)

7

In [16]:
df_mapper_col_headers.loc[ObjectId("5c056a4f0a82861e733374ef")]["name"]

'Identification du marché public'

In [14]:
# df_mapper_col_headers.to_dict('index')

In [237]:
### store dsi_to_dmf apart
prj_dsi_mapping = dso_mapping["dsi_to_dmf"] 
#pp.pprint(prj_dsi_mapping)

In [238]:
df_mapper_dsi_to_dmf = pd.DataFrame(prj_dsi_mapping)
df_mapper_dsi_to_dmf = df_mapper_dsi_to_dmf.set_index(["oid_dsi","oid_dmf"])
df_mapper_dsi_to_dmf

                                                          dsi_header
oid_dsi                  oid_dmf
5c3758200a828696f74fcfe3 5c3777d10a8286e874b46075           added_at
                         5ba664030a82860745d51fdd  adresse du projet
                         5c056a4f0a82861e733374ef                _id
                         5bf4183f0a8286180b53183c          link_data
5c3758690a828696f74fcfe5 5c10443c0a8286a6f6522dfe              CAPAY
                         5ba664030a82860745d51fdd             ACTUAL

In [239]:
len(df_mapper_dsi_to_dmf.index)

6

In [240]:
# df_mapper_dsi_to_dmf.to_dict('index')

In [241]:
df_mapper_dsi_to_dmf#.reset_index()

                                                          dsi_header
oid_dsi                  oid_dmf
5c3758200a828696f74fcfe3 5c3777d10a8286e874b46075           added_at
                         5ba664030a82860745d51fdd  adresse du projet
                         5c056a4f0a82861e733374ef                _id
                         5bf4183f0a8286180b53183c          link_data
5c3758690a828696f74fcfe5 5c10443c0a8286a6f6522dfe              CAPAY
                         5ba664030a82860745d51fdd             ACTUAL

In [242]:
def dsi_remap (dsi_data, df_mapper_dsi_to_dmf, df_mapper_col_headers ) : 

    ### add df_mapper_dsi_to_dmf from df_mapper_col_headers
    df_oid 		 = dsi_data["oid_dsi"]
    df_map_light = df_mapper_dsi_to_dmf.loc[df_oid]
    df_map 		 = pd.merge(df_map_light, df_mapper_col_headers, on=['oid_dmf']).reset_index()
    df_map_ 	 = df_map.set_index('dsi_header')
    
    ### list cols to keep : present in dsi and mapped
    # df_cols_to_keep  = list(df_map['dsi_header'])
    df_cols_to_keep  = list(df_map_.index)

    ### generate df from dsi_data
    df_ = pd.DataFrame(dsi_data["data_raw"]["f_data"])
    ### drop useless columns in df_
    df_cols 			= list(df_.columns)
    df_cols_to_drop 	= [ h for h in df_cols if h not in df_cols_to_keep ]
    df_light 			= df_.drop( df_cols_to_drop, axis=1 )

    ### rename columns dataframe
    remapper_dict		= dict(df_map_['name'])
    df_light.columns 	= df_light.columns.to_series().map(remapper_dict)
    print()

    return df_light

In [243]:
df_01_light = dsi_remap(dsi_data_01, df_mapper_dsi_to_dmf, df_mapper_col_headers)
df_01_light

,Identification du marché public,Adresse_
0,5bcdc4dc3ba14c6ce4c3426e,"[2 633 276 €, : Lorraine, FEDER, 2013, 842 634..."
1,5bd0895e3ba14c3fada0550e,"[Opération ""Eté Jeunes"" pour les 14-16 ans Ger..."
2,5bd08f1b3ba14c3fada05cd8,"[A Eaubonne, les jeunes en service civique aid..."

In [244]:
df_02_light = dsi_remap(dsi_data_02, df_mapper_dsi_to_dmf, df_mapper_col_headers)
df_02_light

   Adresse_ Code du lieu d'exécution
0         1                     None
1         3                     None
2         1                     None
3         1                     None
4         1                     None
5         1                     None
6         2                     None

In [245]:
df_data_concat = pd.concat([df_01_light, df_02_light], ignore_index=True, sort=False)
df_data_concat = df_data_concat.replace({np.nan:None})
df_data_concat

,Identification du marché public,Adresse_,Code du lieu d'exécution
0,5bcdc4dc3ba14c6ce4c3426e,"[2 633 276 €, : Lorraine, FEDER, 2013, 842 634...",None
1,5bd0895e3ba14c3fada0550e,"[Opération ""Eté Jeunes"" pour les 14-16 ans Ger...",None
2,5bd08f1b3ba14c3fada05cd8,"[A Eaubonne, les jeunes en service civique aid...",None
3,None,1,None
4,None,3,None
5,None,1,None
6,None,1,None
7,None,1,None
8,None,1,None
9,None,2,None

In [246]:
df_data_concat.to_dict('records')

[{'Identification du marché public': '5bcdc4dc3ba14c6ce4c3426e',
  'Adresse_': ['2 633 276 €',
   ': Lorraine',
   'FEDER',
   '2013',
   '842 634 €',
   'Lorraine',
   'FEDER',
   '2013'],
  "Code du lieu d'exécution": None},
 {'Identification du marché public': '5bd0895e3ba14c3fada0550e',
  'Adresse_': ['Opération "Eté Jeunes" pour les 14-16 ans Gers',
   '32360 Jegun',
   "Les députés votent la substitution du CNDS par l'Agence nationale du sport et gonflent son budget",
   'Lancement de France Num, une plateforme nationale pour accompagner la transformation numérique des TPE',
   'Grande Rue - BP1',
   'Volet "finances locales" : le point après le vote par les députés de la première partie du texte',
   "Enfin des stats sur le poids de l'habitat privé dans les quartiers prioritaires !"],
  "Code du lieu d'exécution": None},
 {'Identification du marché public': '5bd08f1b3ba14c3fada05cd8',
  'Adresse_': ["A Eaubonne, les jeunes en service civique aident des familles à réduire leurs factures d'énergie (95) Val-d'Oise",
   "Hôtel de Ville, 1 rue d'Enghien",
   "Les députés votent la substitution du CNDS par l'Agence nationale du sport et gonflent son budget",
   'Lancement de France Num, une plateforme nationale pour accompagner la transformation numérique des TPE',
   '95600 Eaubonne',
   'Volet "finances locales" : le point après le vote par les députés de la première partie du texte',
   "Enfin des stats sur le poids de l'habitat privé dans les quartiers prioritaires !"],
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 1,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 3,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 1,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 1,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 1,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 1,
  "Code du lieu d'exécution": None},
 {'Identification du marché public': None,
  'Adresse_': 2,
  "Code du lieu d'exécution": None}]

In [188]:
### add df_mapper_dsi_to_dmf from df_mapper_col_headers
df_01_oid = dsi_data_01["oid_dsi"]
df_map_01 = df_mapper_dsi_to_dmf.loc[df_01_oid]
df_map_01

                                 dsi_header
oid_dmf
5c3777d10a8286e874b46075           added_at
5ba664030a82860745d51fdd  adresse du projet
5c056a4f0a82861e733374ef                _id
5bf4183f0a8286180b53183c          link_data

In [189]:
### 
df_map_01_ = pd.merge(df_map_01, df_mapper_col_headers, on=['oid_dmf']).reset_index()
df_map_01_ = df_map_01_.set_index('dsi_header')
df_map_01_

,oid_dmf,name,open_level_show
dsi_header,,,
adresse du projet,5ba664030a82860745d51fdd,Adresse_,open_data
_id,5c056a4f0a82861e733374ef,Identification du marché public,open_data

In [190]:
df_01_cols_to_keep = list(df_map_01_.index)
df_01_cols_to_keep

['adresse du projet', '_id']

In [191]:
remapper_dict = dict(df_map_01_['name'])
remapper_dict

{'adresse du projet': 'Adresse_', '_id': 'Identification du marché public'}

In [192]:
df_01 = pd.DataFrame(dsi_data_01["data_raw"]["f_data"])
df_01.head(2)

,_id,added_at,adresse du projet,image(s) du projet,link_data,link_src,partenaires du projet,résumé du projet,spider_id,structure porteuse,tags,titre du projet,website
0,5bcdc4dc3ba14c6ce4c3426e,1.540212e+09,"[2 633 276 €, : Lorraine, FEDER, 2013, 842 634...",[http://www.europe-en-france.gouv.fr/var/europ...,http://www.europe-en-france.gouv.fr/Rendez-vou...,http://www.europe-en-france.gouv.fr/Rendez-vou...,"[2 633 276 €, : Lorraine, FEDER, 2013, 842 634...","[La fibre de verre, considérée comme un matéri...",5ac3505d0a82860f68d16288,[Thématique(s) : Attractivité du territoire ; ...,[Thématique(s) : Attractivité du territoire ; ...,[Le projet Fibrastral développe une alternativ...,None
1,5bd0895e3ba14c3fada0550e,1.540392e+09,"[Opération ""Eté Jeunes"" pour les 14-16 ans Ger...",None,https://www.caissedesdepotsdesterritoires.fr/c...,https://www.caissedesdepotsdesterritoires.fr/c...,None,[La communauté de communes Coeur de Gascogne a...,5bc4951d3ba14c5c5620146c,None,"[SOCIAL - SANTÉ, CATÉGORIE : EXPÉRIENCES, Soci...","[Opération ""Eté Jeunes"" pour les 14-16 ans]",None

In [193]:
df_01_cols = list(df_01.columns)
df_01_cols_to_drop = [ h for h in df_01_cols if h not in df_01_cols_to_keep ]
df_01_cols_to_drop

['added_at',
 'image(s) du projet',
 'link_data',
 'link_src',
 'partenaires du projet',
 'résumé du projet',
 'spider_id',
 'structure porteuse',
 'tags',
 'titre du projet',
 'website']

In [194]:
df_01_light = df_01.drop( df_01_cols_to_drop, axis=1 )
df_01_light.head(2)

                        _id                                  adresse du projet
0  5bcdc4dc3ba14c6ce4c3426e  [2 633 276 €, : Lorraine, FEDER, 2013, 842 634...
1  5bd0895e3ba14c3fada0550e  [Opération "Eté Jeunes" pour les 14-16 ans Ger...

In [195]:
### rename columns
df_01_light.columns = df_01_light.columns.to_series().map(remapper_dict)
df_01_light

,Identification du marché public,Adresse_
0,5bcdc4dc3ba14c6ce4c3426e,"[2 633 276 €, : Lorraine, FEDER, 2013, 842 634..."
1,5bd0895e3ba14c3fada0550e,"[Opération ""Eté Jeunes"" pour les 14-16 ans Ger..."
2,5bd08f1b3ba14c3fada05cd8,"[A Eaubonne, les jeunes en service civique aid..."

In [35]:
df_01_oid = dsi_data_01["oid_dsi"]
df_map_01 = df_mapper_multiindexed.loc[df_01_oid]
df_map_01

,oid_dmf,name,oid_dmf,open_level_show
dsi_header,,,,
added_at,5c3777d10a8286e874b46075,Identification du marché public,5c056a4f0a82861e733374ef,open_data
adresse du projet,5ba664030a82860745d51fdd,Date de la notification du marché,5c10450f0a8286a6f6522e02,open_data
_id,5c056a4f0a82861e733374ef,NaN,5c10456e0a8286a6f6522e04,private
link_data,5bf4183f0a8286180b53183c,Nom de l'acheteur,5bfe87520a82866842b7db96,collective

In [36]:
df_map_01.to_dict('index')

/Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_solidata/backend/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  """Entry point for launching an IPython kernel.

{'added_at': {'oid_dmf': ObjectId('5c056a4f0a82861e733374ef'),
  'name': 'Identification du marché public',
  'open_level_show': 'open_data'},
 'adresse du projet': {'oid_dmf': ObjectId('5c10450f0a8286a6f6522e02'),
  'name': 'Date de la notification du marché',
  'open_level_show': 'open_data'},
 '_id': {'oid_dmf': ObjectId('5c10456e0a8286a6f6522e04'),
  'name': nan,
  'open_level_show': 'private'},
 'link_data': {'oid_dmf': ObjectId('5bfe87520a82866842b7db96'),
  'name': "Nom de l'acheteur",
  'open_level_show': 'collective'}}

In [ ]:
def dsi_remap (dsi_data, prj_dsi_mapping, df_mapper_multiindexed ) : 

    ### generate df from dsi_data
    df_oid 	= dsi_data["oid_dsi"]
    df_ 	= pd.DataFrame(dsi_data["data_raw"]["f_data"])
    print("df_ ...")
    print(df_)
    
    ### get 
    df_map_ = df_mapper_multiindexed.loc[df_oid]

    ### get current dsi's map from prj_dsi_mapping
    df_map 	= [ h for h in prj_dsi_mapping if h["oid_dsi"] == df_oid ]
    print()

    ### drop useless columns 
    df_cols 			= list(df_.columns)
    df_cols_to_keep  	= [ h["dsi_header"] for h in df_map if h["dsi_header"] in df_cols ] 
    df_cols_to_drop 	= [ h for h in df_cols if h not in df_cols_to_keep ]
    df_light 			= df_.drop( df_cols_to_drop, axis=1 )
    print("df_light ...")
    print(df_light)

    ### rename columns dataframe
    df_mapper_ 			= df_mapper_.reset_index().set_index('dsi_header')
    df_mapper_dict_name = df_mapper_["name"].to_dict()
    print("df_mapper_dict_name : \n", df_mapper_dict_name)
    
    ### remap
    df_light.columns 	= df_light.columns.to_series().map(df_mapper_dict_name)
    print("df_light ...")
    print(df_light)

    return df_light

In [ ]:
df_01 	= pd.DataFrame(dsi_data_01["data_raw"]["f_data"])
df_01

In [ ]:
df_01_light_ = dsi_remap(dsi_data_01, prj_dsi_mapping, df_mapper_reindexed)
df_01_light_

In [ ]:

### generate df from dsi_01
df_01_oid = dsi_data_01["oid_dsi"]

df_01_map = [ h for h in prj_dsi_mapping if h["oid_dsi"] == df_01_oid ]
print ("df_01_map :")
pp.pprint ( df_01_map)

df_01 = pd.DataFrame(dsi_data_01["data_raw"]["f_data"])
df_01.head(3)

In [ ]:
### drop useless columns 
df_01_cols = list(df_01.columns)
df_01_cols_to_keep  = [ h["dsi_header"] for h in df_01_map if h["dsi_header"] in df_01_cols ] 
print("df_01_cols_to_keep :") 
pp.pprint(df_01_cols_to_keep)

df_01_cols_to_drop = [ h for h in df_01_cols if h not in df_01_cols_to_keep ]
print("df_01_cols_to_drop :") 
pp.pprint(df_01_cols_to_drop)

In [ ]:
df_01_light = df_01.drop( df_01_cols_to_drop, axis=1 )
df_01_light

In [ ]:
### generate df from dsi_01
df_02_oid = dsi_data_02["oid_dsi"]

df_02_map = [ header for header in prj_dsi_mapping if header["oid_dsi"] == df_02_oid ]
print ("df_02_map :")
pp.pprint ( df_02_map)

df_02 = pd.DataFrame(dsi_data_02["data_raw"]["f_data"])
print ("df_02 : ")
df_02.head(3)

In [ ]:
### drop useless columns 
df_02_cols = list(df_02.columns)
df_02_cols_to_keep  = [ h["dsi_header"] for h in df_02_map if h["dsi_header"] in df_02_cols ] 
df_02_cols_to_drop = [ h for h in df_02_cols if h not in df_02_cols_to_keep ]
df_02_cols_to_drop

In [ ]:
df_02_light = df_02.drop( df_02_cols_to_drop, axis=1 )
df_02_light

In [ ]:
df_mapper_02 = df_mapper_reindexed[df_mapper_reindexed.oid_dsi == df_02_oid ]
df_mapper_02 = df_mapper_02.reset_index().set_index('dsi_header')
df_mapper_02

In [ ]:

df_mapper_dict_name = df_mapper_02["name"].to_dict()
print (df_mapper_dict_name)

In [ ]:
df_02_light.columns = df_02_light.columns.to_series().map(df_mapper_dict_name)
df_02_light

In [ ]:

result = pd.concat([df_01_light, df_02_light], ignore_index=True)
result